### ISSUE TITLE
Add documentation website

### ISSUE THREAD

**Issue by VaibhavSys** [AnonymousDebug/sweat-smacker-bot-discord#81]
https://ball.mousemoosz.is-a.dev (Not ready yet)

**Comment by candyrainfall** [comment]
Do you have any other documentation you need done?

**Comment by VaibhavSys** [comment]
> Do you have any other documentation you need done?

Yes, commands need to be documented and instructions for how to deploy to replit, heroku and railway need to be added.

**Comment by candyrainfall** [comment]
> 

I would love to help with that.

**Comment by VaibhavSys** [comment]
> > 
> 
> I would love to help with that.

Thanks! We will be using [mkdocs](https://www.mkdocs.org) and the development branch is attached with the PR

**Comment by candyrainfall** [comment]
I've installed mkdocs but I'm having a bit of trouble finding the PR. Still getting used to git and the command line

**Comment by VaibhavSys** [comment]
> I've installed mkdocs but I'm having a bit of trouble finding the PR. Still getting used to git and the command line

This is not a PR, this is an issue. You can checkout the development branch for this docs via `git checkout 81-add-documentation-website`
